### ISSUE TITLE
Clone and run leads to:  thread 'main' panicked at src/app.rs:32:61: called `Result::unwrap()` on an `Err` value: "File doesn't exist!"

### ISSUE THREAD

**Issue by nerdachse** [ria8651/octree-tracer#1]
Hello!

As stated above, a simple `git clone` and `cargo run --release` leads to the error:

> thread 'main' panicked at src/app.rs:32:61:
> called `Result::unwrap()` on an `Err` value: "File doesn't exist!"

**Comment by ria8651** [comment]
I just had some paths that only worked on my computer. Should be fixed now.

I suspect you'll have the same issue as on the other repo though as I have multiple COPY_DST and MAP_READ buffers.

**Comment by mogambro** [comment]
Thanks! It starts, because wgpu 0.12 didn't have this issue.

Then I open a file:

```
octree-tracer v0.1.0
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...
Cataloged 0 million nodes
Mip success!
Staring to mip...                                                                  Staring to mip...ion nodes
Cataloged 0 million nodes
Cataloged 1 million nodes
Cataloged 2 million nodes
Cataloged 3 million nodes
Cataloged 4 million nodes
Cataloged 5 million nodes
Cataloged 6 million nodes
Cataloged 7 million nodes
Cataloged 8 million nodes
Cataloged 9 million nodes
Cataloged 10 million nodes
Cataloged 11 million nodes
Mip success!```


But the screen stays black, so while it doesn't crash it doesn't work either :D
